#colocar aq os inserts por padrao
INSERT INTO estilos_de_jogo (nome)
VALUES 
	('Chute Colocado'),
	('Cavadinha'),
	('Testada Firme'),
	('Super Chute'),
	('Bola Parada'),
	('Passe Incisivo'),
	('Passe Preciso'),
	('Tiki-Taka'),
	('Passe Longo'),
	('Passe de GPS'),
	('Dominio'),
	('Firula'),
	('Cabeca Fria'),
	('Veloz'),
	('Tecnica'),
	('Malvedeza'),
	('Barreira'),
	('Xerife'),
	('Interceptacao'),
	('Cercar'),
	('Carrinho Limpo'),
	('Antecipacao'),
	('Acrobata'),
	('Jogo Aereo'),
	('Trivela'),
	('Incansavel'),
	('Passos Largos'),
	('Lateral Longo'),
	('Arremeco Longo'),
	('Usa os pes'),
	('Saida Aerea'),
	('Sai que e sua'),
	('Braco Elastico'),
	('Reflexo Rapido');